version: 2.1

references:
  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      version: {}

executors:
  go-executor:
    docker:
      - image: cimg/go:1.22.5
    working_directory: ~/repo

commands:
  docker_hub_auth:
    steps:
      - *setup_remote_docker
      - run:
          name: Docker login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin

jobs:
  lint:
    executor: go-executor
    steps:
      - checkout
      - docker_hub_auth
      - run:
          name: Install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - run:
          name: Run golangci-lint
          command: golangci-lint run
  test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            go mod download
            go install github.com/golang/mock/mockgen@v1.6.0
      - run:
          name: Generate Mocks
          command: |
            mockgen -source=repository/account_repository.go -destination=mocks/mock_account_repository.go -package=mocks
      - run:
          name: Run tests
          command: go test -v ./test/...

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test:
          requires:
            - lint
