version: 2.1

jobs:
  lint:
    docker:
      - image: img/go:1.22.5
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b "$(go env GOPATH)/bin"
      - run:
          name: Run golangci-lint
          command: golangci-lint run

workflows:
  version: 2
  development:
    jobs:
      - lint
