// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/domain/repository/status.go
//
// Generated by this command:
//
//	mockgen -source=./app/domain/repository/status.go -destination=./app/domain/repository/mocks/mock_status.go
//

// Package mock_repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	object "yatter-backend-go/app/domain/object"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockStatus is a mock of Status interface.
type MockStatus struct {
	ctrl     *gomock.Controller
	recorder *MockStatusMockRecorder
}

// MockStatusMockRecorder is the mock recorder for MockStatus.
type MockStatusMockRecorder struct {
	mock *MockStatus
}

// NewMockStatus creates a new mock instance.
func NewMockStatus(ctrl *gomock.Controller) *MockStatus {
	mock := &MockStatus{ctrl: ctrl}
	mock.recorder = &MockStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatus) EXPECT() *MockStatusMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStatus) Create(ctx context.Context, tx *sqlx.Tx, st *object.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStatusMockRecorder) Create(ctx, tx, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStatus)(nil).Create), ctx, tx, st)
}

// FindByID mocks base method.
func (m *MockStatus) FindByID(ctx context.Context, id string) (*object.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*object.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStatusMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStatus)(nil).FindByID), ctx, id)
}

// FindPublicTimeline mocks base method.
func (m *MockStatus) FindPublicTimeline(ctx context.Context, limit int) ([]*object.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublicTimeline", ctx, limit)
	ret0, _ := ret[0].([]*object.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPublicTimeline indicates an expected call of FindPublicTimeline.
func (mr *MockStatusMockRecorder) FindPublicTimeline(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublicTimeline", reflect.TypeOf((*MockStatus)(nil).FindPublicTimeline), ctx, limit)
}
